# product environment use application.properties
# don't pulish
server.tomcat.accesslog.enabled=false
server.tomcat.basedir=
springdoc.enable=true
# need pulish
# base
# DB
datasource.host=127.0.0.1
datasource.port=3306
datasource.username=root
datasource.password=12345678
# cors
app.cors.enable=true

